Update
stonyte1/nba pull request #7
Opened 2023-04-26 17:42 UTC by stonyte1

2023-04-26 18:26 UTC, sstInfare requested changes

2023-04-26 18:26 UTC, sstInfare commented on games.py
> +class Player():
this probably represents not a player, but a game performance of specific player on specific game

2023-04-26 18:26 UTC, sstInfare commented on games.py
> +with open('%s.txt' % yesterday_date, 'w') as file:
move this inside wile loop in line 24, so you open the file once per while loop

2023-04-27 06:48 UTC, stonyte1 commented
Done

2023-04-27 06:48 UTC, merged